global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'lsm-bot'
    static_configs:
      - targets: ['host.docker.internal:9100']
        labels:
          bot: 'BotA'

  - job_name: 'lsm-bot-alt'
    static_configs:
      - targets: ['172.17.0.1:9100']
        labels:
          bot: 'BotA-alt'
